# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
notifications:
  email: false
jobs:
  include:
    - os: linux
      arch: x64
      julia: 1
    - os: linux
      arch: x86  # Test 32-bit
      julia: 1
    - os: linux
      arch: x64
      julia: nightly
      allow_failure: true
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
